// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: apache/rocketmq/v2/admin.proto

package rocketmqv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_ChangeLogLevel_FullMethodName            = "/apache.rocketmq.v2.Admin/ChangeLogLevel"
	Admin_DescribeTopicStatus_FullMethodName       = "/apache.rocketmq.v2.Admin/DescribeTopicStatus"
	Admin_ListSubscription_FullMethodName          = "/apache.rocketmq.v2.Admin/ListSubscription"
	Admin_DescribeSubscription_FullMethodName      = "/apache.rocketmq.v2.Admin/DescribeSubscription"
	Admin_DeleteSubscription_FullMethodName        = "/apache.rocketmq.v2.Admin/DeleteSubscription"
	Admin_DescribeGroupAccumulation_FullMethodName = "/apache.rocketmq.v2.Admin/DescribeGroupAccumulation"
	Admin_ListConsumerConnection_FullMethodName    = "/apache.rocketmq.v2.Admin/ListConsumerConnection"
	Admin_ResetGroupOffset_FullMethodName          = "/apache.rocketmq.v2.Admin/ResetGroupOffset"
	Admin_QueryMessage_FullMethodName              = "/apache.rocketmq.v2.Admin/QueryMessage"
	Admin_PrintThreadStackTrace_FullMethodName     = "/apache.rocketmq.v2.Admin/PrintThreadStackTrace"
	Admin_VerifyMessage_FullMethodName             = "/apache.rocketmq.v2.Admin/VerifyMessage"
	Admin_AdminSendMessage_FullMethodName          = "/apache.rocketmq.v2.Admin/AdminSendMessage"
	Admin_GetConsumerRunningInfo_FullMethodName    = "/apache.rocketmq.v2.Admin/GetConsumerRunningInfo"
	Admin_GetTopicRoute_FullMethodName             = "/apache.rocketmq.v2.Admin/GetTopicRoute"
	Admin_QueryTimeSpan_FullMethodName             = "/apache.rocketmq.v2.Admin/QueryTimeSpan"
	Admin_GetProxyRuntimeStats_FullMethodName      = "/apache.rocketmq.v2.Admin/GetProxyRuntimeStats"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Admin exposes control-plane operations for cluster administration and
// diagnostics over gRPC, complementing the data-plane MessagingService.
type AdminClient interface {
	// Dynamically change the server log level.
	ChangeLogLevel(ctx context.Context, in *ChangeLogLevelRequest, opts ...grpc.CallOption) (*ChangeLogLevelResponse, error)
	// Describe the status and metadata of a topic.
	DescribeTopicStatus(ctx context.Context, in *DescribeTopicStatusRequest, opts ...grpc.CallOption) (*DescribeTopicStatusResponse, error)
	// List subscription relationships filtered by topic and/or group.
	ListSubscription(ctx context.Context, in *ListSubscriptionRequest, opts ...grpc.CallOption) (*ListSubscriptionResponse, error)
	// Describe subscriptions grouped per connected client.
	DescribeSubscription(ctx context.Context, in *DescribeSubscriptionRequest, opts ...grpc.CallOption) (*DescribeSubscriptionResponse, error)
	// Delete a subscription relationship.
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error)
	// Query the message accumulation (lag) of a consumer group.
	DescribeGroupAccumulation(ctx context.Context, in *DescribeGroupAccumulationRequest, opts ...grpc.CallOption) (*DescribeGroupAccumulationResponse, error)
	// List online consumer connections of a group.
	ListConsumerConnection(ctx context.Context, in *ListConsumerConnectionRequest, opts ...grpc.CallOption) (*ListConsumerConnectionResponse, error)
	// Reset the consume offset of a group to a timestamp.
	ResetGroupOffset(ctx context.Context, in *ResetGroupOffsetRequest, opts ...grpc.CallOption) (*ResetGroupOffsetResponse, error)
	// Query messages by id, key or subscription within a time range.
	QueryMessage(ctx context.Context, in *ListMessageRequest, opts ...grpc.CallOption) (*ListMessageResponse, error)
	// Print the thread stack trace of a client.
	PrintThreadStackTrace(ctx context.Context, in *PrintThreadStackTraceRequest, opts ...grpc.CallOption) (*PrintThreadStackTraceResponse, error)
	// Verify consumption of a message by a specific client.
	VerifyMessage(ctx context.Context, in *VerifyMessageRequest, opts ...grpc.CallOption) (*VerifyMessageResponse, error)
	// Send a message from the admin side (e.g. a console test message).
	AdminSendMessage(ctx context.Context, in *AdminSendMessageRequest, opts ...grpc.CallOption) (*AdminSendMessageResponse, error)
	// Fetch aggregated running information of a consumer client.
	GetConsumerRunningInfo(ctx context.Context, in *GetConsumerRunningInfoRequest, opts ...grpc.CallOption) (*GetConsumerRunningInfoResponse, error)
	// Query the route data of a topic.
	GetTopicRoute(ctx context.Context, in *GetTopicRouteRequest, opts ...grpc.CallOption) (*GetTopicRouteResponse, error)
	// Query the time span of messages consumed by a group.
	QueryTimeSpan(ctx context.Context, in *QueryTimeSpanRequest, opts ...grpc.CallOption) (*QueryTimeSpanResponse, error)
	// Fetch runtime statistics of the serving process.
	GetProxyRuntimeStats(ctx context.Context, in *GetProxyRuntimeStatsRequest, opts ...grpc.CallOption) (*GetProxyRuntimeStatsResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ChangeLogLevel(ctx context.Context, in *ChangeLogLevelRequest, opts ...grpc.CallOption) (*ChangeLogLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeLogLevelResponse)
	err := c.cc.Invoke(ctx, Admin_ChangeLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DescribeTopicStatus(ctx context.Context, in *DescribeTopicStatusRequest, opts ...grpc.CallOption) (*DescribeTopicStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeTopicStatusResponse)
	err := c.cc.Invoke(ctx, Admin_DescribeTopicStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListSubscription(ctx context.Context, in *ListSubscriptionRequest, opts ...grpc.CallOption) (*ListSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubscriptionResponse)
	err := c.cc.Invoke(ctx, Admin_ListSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DescribeSubscription(ctx context.Context, in *DescribeSubscriptionRequest, opts ...grpc.CallOption) (*DescribeSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeSubscriptionResponse)
	err := c.cc.Invoke(ctx, Admin_DescribeSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSubscriptionResponse)
	err := c.cc.Invoke(ctx, Admin_DeleteSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DescribeGroupAccumulation(ctx context.Context, in *DescribeGroupAccumulationRequest, opts ...grpc.CallOption) (*DescribeGroupAccumulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeGroupAccumulationResponse)
	err := c.cc.Invoke(ctx, Admin_DescribeGroupAccumulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListConsumerConnection(ctx context.Context, in *ListConsumerConnectionRequest, opts ...grpc.CallOption) (*ListConsumerConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumerConnectionResponse)
	err := c.cc.Invoke(ctx, Admin_ListConsumerConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ResetGroupOffset(ctx context.Context, in *ResetGroupOffsetRequest, opts ...grpc.CallOption) (*ResetGroupOffsetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetGroupOffsetResponse)
	err := c.cc.Invoke(ctx, Admin_ResetGroupOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) QueryMessage(ctx context.Context, in *ListMessageRequest, opts ...grpc.CallOption) (*ListMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessageResponse)
	err := c.cc.Invoke(ctx, Admin_QueryMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) PrintThreadStackTrace(ctx context.Context, in *PrintThreadStackTraceRequest, opts ...grpc.CallOption) (*PrintThreadStackTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintThreadStackTraceResponse)
	err := c.cc.Invoke(ctx, Admin_PrintThreadStackTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) VerifyMessage(ctx context.Context, in *VerifyMessageRequest, opts ...grpc.CallOption) (*VerifyMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyMessageResponse)
	err := c.cc.Invoke(ctx, Admin_VerifyMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AdminSendMessage(ctx context.Context, in *AdminSendMessageRequest, opts ...grpc.CallOption) (*AdminSendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminSendMessageResponse)
	err := c.cc.Invoke(ctx, Admin_AdminSendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetConsumerRunningInfo(ctx context.Context, in *GetConsumerRunningInfoRequest, opts ...grpc.CallOption) (*GetConsumerRunningInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConsumerRunningInfoResponse)
	err := c.cc.Invoke(ctx, Admin_GetConsumerRunningInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetTopicRoute(ctx context.Context, in *GetTopicRouteRequest, opts ...grpc.CallOption) (*GetTopicRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopicRouteResponse)
	err := c.cc.Invoke(ctx, Admin_GetTopicRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) QueryTimeSpan(ctx context.Context, in *QueryTimeSpanRequest, opts ...grpc.CallOption) (*QueryTimeSpanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTimeSpanResponse)
	err := c.cc.Invoke(ctx, Admin_QueryTimeSpan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetProxyRuntimeStats(ctx context.Context, in *GetProxyRuntimeStatsRequest, opts ...grpc.CallOption) (*GetProxyRuntimeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProxyRuntimeStatsResponse)
	err := c.cc.Invoke(ctx, Admin_GetProxyRuntimeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
//
// Admin exposes control-plane operations for cluster administration and
// diagnostics over gRPC, complementing the data-plane MessagingService.
type AdminServer interface {
	// Dynamically change the server log level.
	ChangeLogLevel(context.Context, *ChangeLogLevelRequest) (*ChangeLogLevelResponse, error)
	// Describe the status and metadata of a topic.
	DescribeTopicStatus(context.Context, *DescribeTopicStatusRequest) (*DescribeTopicStatusResponse, error)
	// List subscription relationships filtered by topic and/or group.
	ListSubscription(context.Context, *ListSubscriptionRequest) (*ListSubscriptionResponse, error)
	// Describe subscriptions grouped per connected client.
	DescribeSubscription(context.Context, *DescribeSubscriptionRequest) (*DescribeSubscriptionResponse, error)
	// Delete a subscription relationship.
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error)
	// Query the message accumulation (lag) of a consumer group.
	DescribeGroupAccumulation(context.Context, *DescribeGroupAccumulationRequest) (*DescribeGroupAccumulationResponse, error)
	// List online consumer connections of a group.
	ListConsumerConnection(context.Context, *ListConsumerConnectionRequest) (*ListConsumerConnectionResponse, error)
	// Reset the consume offset of a group to a timestamp.
	ResetGroupOffset(context.Context, *ResetGroupOffsetRequest) (*ResetGroupOffsetResponse, error)
	// Query messages by id, key or subscription within a time range.
	QueryMessage(context.Context, *ListMessageRequest) (*ListMessageResponse, error)
	// Print the thread stack trace of a client.
	PrintThreadStackTrace(context.Context, *PrintThreadStackTraceRequest) (*PrintThreadStackTraceResponse, error)
	// Verify consumption of a message by a specific client.
	VerifyMessage(context.Context, *VerifyMessageRequest) (*VerifyMessageResponse, error)
	// Send a message from the admin side (e.g. a console test message).
	AdminSendMessage(context.Context, *AdminSendMessageRequest) (*AdminSendMessageResponse, error)
	// Fetch aggregated running information of a consumer client.
	GetConsumerRunningInfo(context.Context, *GetConsumerRunningInfoRequest) (*GetConsumerRunningInfoResponse, error)
	// Query the route data of a topic.
	GetTopicRoute(context.Context, *GetTopicRouteRequest) (*GetTopicRouteResponse, error)
	// Query the time span of messages consumed by a group.
	QueryTimeSpan(context.Context, *QueryTimeSpanRequest) (*QueryTimeSpanResponse, error)
	// Fetch runtime statistics of the serving process.
	GetProxyRuntimeStats(context.Context, *GetProxyRuntimeStatsRequest) (*GetProxyRuntimeStatsResponse, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) ChangeLogLevel(context.Context, *ChangeLogLevelRequest) (*ChangeLogLevelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeLogLevel not implemented")
}
func (UnimplementedAdminServer) DescribeTopicStatus(context.Context, *DescribeTopicStatusRequest) (*DescribeTopicStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeTopicStatus not implemented")
}
func (UnimplementedAdminServer) ListSubscription(context.Context, *ListSubscriptionRequest) (*ListSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubscription not implemented")
}
func (UnimplementedAdminServer) DescribeSubscription(context.Context, *DescribeSubscriptionRequest) (*DescribeSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeSubscription not implemented")
}
func (UnimplementedAdminServer) DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedAdminServer) DescribeGroupAccumulation(context.Context, *DescribeGroupAccumulationRequest) (*DescribeGroupAccumulationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeGroupAccumulation not implemented")
}
func (UnimplementedAdminServer) ListConsumerConnection(context.Context, *ListConsumerConnectionRequest) (*ListConsumerConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConsumerConnection not implemented")
}
func (UnimplementedAdminServer) ResetGroupOffset(context.Context, *ResetGroupOffsetRequest) (*ResetGroupOffsetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetGroupOffset not implemented")
}
func (UnimplementedAdminServer) QueryMessage(context.Context, *ListMessageRequest) (*ListMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMessage not implemented")
}
func (UnimplementedAdminServer) PrintThreadStackTrace(context.Context, *PrintThreadStackTraceRequest) (*PrintThreadStackTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintThreadStackTrace not implemented")
}
func (UnimplementedAdminServer) VerifyMessage(context.Context, *VerifyMessageRequest) (*VerifyMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyMessage not implemented")
}
func (UnimplementedAdminServer) AdminSendMessage(context.Context, *AdminSendMessageRequest) (*AdminSendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminSendMessage not implemented")
}
func (UnimplementedAdminServer) GetConsumerRunningInfo(context.Context, *GetConsumerRunningInfoRequest) (*GetConsumerRunningInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsumerRunningInfo not implemented")
}
func (UnimplementedAdminServer) GetTopicRoute(context.Context, *GetTopicRouteRequest) (*GetTopicRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopicRoute not implemented")
}
func (UnimplementedAdminServer) QueryTimeSpan(context.Context, *QueryTimeSpanRequest) (*QueryTimeSpanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTimeSpan not implemented")
}
func (UnimplementedAdminServer) GetProxyRuntimeStats(context.Context, *GetProxyRuntimeStatsRequest) (*GetProxyRuntimeStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxyRuntimeStats not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_ChangeLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ChangeLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ChangeLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ChangeLogLevel(ctx, req.(*ChangeLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DescribeTopicStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeTopicStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DescribeTopicStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DescribeTopicStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DescribeTopicStatus(ctx, req.(*DescribeTopicStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListSubscription(ctx, req.(*ListSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DescribeSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DescribeSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DescribeSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DescribeSubscription(ctx, req.(*DescribeSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DescribeGroupAccumulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeGroupAccumulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DescribeGroupAccumulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DescribeGroupAccumulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DescribeGroupAccumulation(ctx, req.(*DescribeGroupAccumulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListConsumerConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsumerConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListConsumerConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListConsumerConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListConsumerConnection(ctx, req.(*ListConsumerConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ResetGroupOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetGroupOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ResetGroupOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ResetGroupOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ResetGroupOffset(ctx, req.(*ResetGroupOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_QueryMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).QueryMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_QueryMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).QueryMessage(ctx, req.(*ListMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_PrintThreadStackTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintThreadStackTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).PrintThreadStackTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_PrintThreadStackTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).PrintThreadStackTrace(ctx, req.(*PrintThreadStackTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_VerifyMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).VerifyMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_VerifyMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).VerifyMessage(ctx, req.(*VerifyMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AdminSendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminSendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminSendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminSendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminSendMessage(ctx, req.(*AdminSendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetConsumerRunningInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsumerRunningInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetConsumerRunningInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetConsumerRunningInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetConsumerRunningInfo(ctx, req.(*GetConsumerRunningInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetTopicRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetTopicRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetTopicRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetTopicRoute(ctx, req.(*GetTopicRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_QueryTimeSpan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTimeSpanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).QueryTimeSpan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_QueryTimeSpan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).QueryTimeSpan(ctx, req.(*QueryTimeSpanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetProxyRuntimeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxyRuntimeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetProxyRuntimeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetProxyRuntimeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetProxyRuntimeStats(ctx, req.(*GetProxyRuntimeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apache.rocketmq.v2.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeLogLevel",
			Handler:    _Admin_ChangeLogLevel_Handler,
		},
		{
			MethodName: "DescribeTopicStatus",
			Handler:    _Admin_DescribeTopicStatus_Handler,
		},
		{
			MethodName: "ListSubscription",
			Handler:    _Admin_ListSubscription_Handler,
		},
		{
			MethodName: "DescribeSubscription",
			Handler:    _Admin_DescribeSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _Admin_DeleteSubscription_Handler,
		},
		{
			MethodName: "DescribeGroupAccumulation",
			Handler:    _Admin_DescribeGroupAccumulation_Handler,
		},
		{
			MethodName: "ListConsumerConnection",
			Handler:    _Admin_ListConsumerConnection_Handler,
		},
		{
			MethodName: "ResetGroupOffset",
			Handler:    _Admin_ResetGroupOffset_Handler,
		},
		{
			MethodName: "QueryMessage",
			Handler:    _Admin_QueryMessage_Handler,
		},
		{
			MethodName: "PrintThreadStackTrace",
			Handler:    _Admin_PrintThreadStackTrace_Handler,
		},
		{
			MethodName: "VerifyMessage",
			Handler:    _Admin_VerifyMessage_Handler,
		},
		{
			MethodName: "AdminSendMessage",
			Handler:    _Admin_AdminSendMessage_Handler,
		},
		{
			MethodName: "GetConsumerRunningInfo",
			Handler:    _Admin_GetConsumerRunningInfo_Handler,
		},
		{
			MethodName: "GetTopicRoute",
			Handler:    _Admin_GetTopicRoute_Handler,
		},
		{
			MethodName: "QueryTimeSpan",
			Handler:    _Admin_QueryTimeSpan_Handler,
		},
		{
			MethodName: "GetProxyRuntimeStats",
			Handler:    _Admin_GetProxyRuntimeStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apache/rocketmq/v2/admin.proto",
}
